 <div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/colaboradores/index" title="Colaboradores" class="tip-bottom current"><i class="icon-user"></i> Colaboradores</a>
    </div>
  </div>
<div class="container-fluid">
    <br>
    <a class="btn btn-success" onclick="javascript:alert('Este recurso não esta liberado para esta versão.')" href="#<?php #echo $this->url('colaboradores', array('action' => 'novo'))?>">Novo Colaborador</a>
    <div class="row-fluid">
      <div class="span12">
          
        <div class="widget-box">
          <div class="widget-title">
             <span class="icon"><i class="icon-th"></i></span> 
            <h5>Lista de Colaboradores</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
              <thead>
                <tr>
                   <th>#</th>
                    <th>Nome</th>
                    <th>Tipo</th>                      
                    <th>Tel. Principal</th>
                    <th>Ação</th>  
                </tr>
              </thead>
              <tbody>
                  <?php 
                  $i=0;
                  foreach($this->aColaboradores as $oColaboradores){ 
                      if($i%2){
                          $grade = "gradeX";
                      }else{
                          $grade = "gradeC";
                      }
                      ?>
                    <tr class="<?php echo $grade; ?>">
                        <td><?php echo $oColaboradores->getCoColaborador(); ?></td>
                        <td><?php echo $oColaboradores->getNoColaborador(); ?></td>
                        <td><?php echo $oColaboradores->getTipoPessoa(); ?></td>
                        <td><?php echo $oColaboradores->getDsTelefone(); ?></td>
                        <td>
                            <a class="btn btn-mini btn-info" href="<?php echo $this->url('colaboradores', array("action" => "detalhes", "id" => $oColaboradores->getCoColaborador())); ?>">Visualizar</a>
                            <a class="btn btn-mini btn-warning" href="<?php echo $this->url('colaboradores', array("action" => "editar", "id" => $oColaboradores->getCoColaborador())); ?>">Editar</a>
                            <?php if(!$oColaboradores->getTpAdministrador()){ ?>
                            <a class="btn btn-mini btn-danger" href="<?php echo $this->url('colaboradores', array("action" => "deletar", "id" => $oColaboradores->getCoColaborador())); ?>">Apagar</a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>