<script src="/js/maruti.form_validation.js"></script>
<script src="/js/maruti.form_common.js"></script>
<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/colaboradores/index" title="Lista de colaboradores" class="tip-bottom">
            <i class="icon-user"></i> Colaboradores</a>
        <a href="/colaboradores/novo" title="Novo Colaborador" class="tip-bottom current">Novo</a>
    </div>
  </div>
 <div class="container-fluid">
        <div class="row-fluid">
          <div class="span6">
            <div class="widget-box">
              <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Cadastro de Colaboradores</h5>
              </div>
              <div class="widget-content nopadding">
                 <form method="POST" action="<?php echo $this->url('colaboradores', array('action' => 'adicionar')); ?>" class="form-horizontal"  name="password_validate" id="password_validate" novalidate="novalidate">
                  
                  <div class="control-group">
                    <label class="control-label">Nome:</label>
                    <div class="controls">                      
                        <input type="text" name="NoColaborador" value=""  id="required">
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">E-Mail:</label>
                    <div class="controls" id="addEmail">
                        <input type="text" name="DsEmail" id="required" value="" >
                    </div>
                  </div>
                     <div class="control-group">
                    <label class="control-label">Telefone:</label>
                    <div class="controls" id="addEmail">
                        <input type="text" name="DsTelefone" id="DsTelefone" value="">
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Senha de acesso:</label>
                    <div class="controls">
                        <input type="password" name="DsSenha" id="DsSenha" value="">
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Confirme senha de acesso:</label>
                    <div class="controls">
                        <input type="password" name="DsSenha2" id="DsSenha2" value="">
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label"  for="TpAdministrador">Administrador:</label>
                    <div class="controls">
                        <label for="TpAdministrador">
                            <input type="checkbox" name="TpAdministrador" id="TpAdministrador" value="true" >
                        </label>
                       
                        <span class="help-block">Administradores podem visualizar e alterar todos os pedidos do sistema.</span> </div>
                  </div>
                     
                  <div class="control-group">
                   
                        <div class="widget-box">
                            <div class="widget-title"> <span class="icon">
                              <div class="checker" id="uniform-title-checkbox">
                                  <i class="icon icon-thumbs-up"></i></div>
                              </span>
                              <h5>Lista de Representadas</h5>
                              
                            </div>
                            <div class="widget-content nopadding">
                              <table class="table table-bordered table-striped">
                                <thead>
                                  <tr>
                                    <th>Representada</th>
                                    <th>Comissão</th>
                                  </tr>
                                </thead>
                                <tbody>
                                    <?php if($representada){ 
                                                foreach($representada as $oRepresentada){ ?>
                                    
                                  <tr>
                                    <td>
                                        <?php echo $oRepresentada->getNoRepresentada(); ?>
                                       
                                    </td>
                                    <td>
                                        <div class="input-append">
                                            <input type="text" name="comissao[<?php echo $oRepresentada->getCoRepresentada(); ?>]" placeholder="5" class="span3">
                                            <span class="add-on">%</span> 
                                        </div> 
                                        
                                    </td>
                                  </tr>
                                    <?php } } ?>
                                 
                                </tbody>
                              </table>
                                
                            </div>
                            <!-- 
                            <span class="help-block">Quais representadas este colaborador vai ter acesso e sua comissão.</span>
                            -->
                          </div>
                   
                      
                  </div> 

                  <div class="form-actions">
                    <button type="submit" class="btn btn-success">Salvar</button>
                    <a href="<?php echo $this->url('colaboradores'); ?>" class="btn">Voltar</a>
                  </div>
                 </form>
              </div>
            </div>
          </div>        
        </div>
        <hr>    
     
</div>    

<script src="/js/maruti.form_common.js"></script> 