<script src="/js/maruti.form_common.js"></script>
<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<?php if(MAP_ENDERECO){ ?>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCfHiSPav6wR-Oj_xWKZAHt6GjNNZJlA3Q&sensor=false"></script>
<?php } ?>

<script>
   <?php if(MAP_ENDERECO){ ?>
    var geocoder;
    var map;
    var marker;

    function initialize() {
        var latlng = new google.maps.LatLng(-22.96842,-43.64109);
        
        var options = {
            zoom: 15,
            center: latlng,
            streetViewControl: false,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            mapTypeControl:false,
            zoomControl: false,
        };

        map = new google.maps.Map(document.getElementById("mapa"), options);

        geocoder = new google.maps.Geocoder();
        
        marker = new google.maps.Marker({
            map: map,
            draggable: false,
        });

        marker.setPosition(latlng);
    }
    <?php } ?>
    $(document).ready(function() {
        <?php if(MAP_ENDERECO){ ?>
        initialize();
        <?php } ?>

        $("#basic_validate_endereco").validate({
            rules: {
                no_logradouro: {
                    required: true
                }
                ,
                nu_cep: {
                    required: true
                }
                ,
                nu_endereco: {
                    required: true
                }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            }
        });
        $(".nu_cep").mask("99999-999");
    });
</script>


<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/clientes/index" title="Lista de Clientes" class="tip-bottom">
            <i class="icon-user"></i> Clientes</a>
        <a href="<?php echo $this->url('clientes', array('action' => 'detalhes', 'id' => $co_pessoa)); ?>" title="Detalhes Cliente" class="tip-bottom">
            <i class="icon-user"></i>  <?php echo $cliente->getNoCliente(); ?></a>
        <a href="<?php echo $this->url('enderecos', array('action' => 'editar', 'idcli' => $co_pessoa)); ?>" title="Novo Endereço" class="tip-bottom current">Novo</a>


    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span6">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> 
                        <i class="icon-align-justify"></i> </span>
                    <h5>Novo Endereço</h5>
                </div>
                <div class="widget-content nopadding">
                    <form method="POST" class="form-horizontal" action="<?php echo $this->url('enderecos', array('action' => 'adicionar')); ?>" name="basic_validate_endereco" id="basic_validate_endereco" novalidate="novalidate">
                        <input type="hidden" value="<?php echo $co_pessoa; ?>" name="co_pessoa" />
                        <div class="control-group">
                            <label class="control-label">Tipo de Endereço</label>
                            <div class="controls">
                                <label>
                                    <input type="radio" name="tp_endereco" value="1" checked="true"  id="tp_endereco" />
                                    Entrega</label>
                                <label>
                                    <input type="radio" name="tp_endereco" value="2"  id="tp_endereco" />
                                    Principal</label>                  
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" id="no_logradouro">Logradouro:</label>
                            <div class="controls">
                                <input type="text" name="no_logradouro" class="span11" placeholder="" id="required" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" id="nu_endereco">Número:</label>
                            <div class="controls">
                                <input type="text"  name="nu_endereco" class="span3" placeholder="" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" id="no_bairro">Bairro:</label>
                            <div class="controls">
                                <input type="text" name="no_bairro"  class="span11" placeholder=""  />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" id="no_cidade">Cidade:</label>
                            <div class="controls">
                                <input type="text"  name="no_cidade" class="span11" placeholder=""  />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" id="co_estado">UF:</label>
                            <div class="controls">
                                <select name="co_estado">
                                    <?php foreach ($uf as $key => $val) { ?>
                                        <option value="<?php echo $key; ?>" ><?php echo $val; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                        <div class="control-group" id="nu_cep"> 
                            <label class="control-label">Cep:</label>
                            <div class="controls">
                                <input type="text"  name="nu_cep" class="span11 nu_cep" placeholder="00000-000" />
                            </div>
                        </div>
                        <div class="control-group" id="nu_latitude"> 
                            <label class="control-label">Latitude:</label>
                            <div class="controls">
                                <input type="text"  name="nu_latitude" class="span11 " placeholder="-22.96842" />
                            </div>
                        </div>
                        <div class="control-group" id="nu_longitude"> 
                            <label class="control-label">Longitude:</label>
                            <div class="controls">
                                <input type="text" name="nu_longitude" class="span11" placeholder="-43.64109" />
                            </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-success">Salvar</button>
                            <a href="<?php echo $this->url('clientes', array('action' => 'detalhes', 'id' => $co_pessoa)); ?>" class="btn">Voltar</a>
                        </div>
                    </form> 
                </div>
            </div>
        </div> 
         <?php if(MAP_ENDERECO){ ?>
            <div class="span4">
                <div class="widget-box">
                    <div class="widget-title"> <span class="icon"> 
                            <i class="icon-align-justify"></i> </span>
                        <h5>Mapa do Endereço</h5>
                    </div>
                    <div class="widget-content nopadding">
                        <div id="mapa" style="width: 396px; height: 255px"></div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <hr>     
</div>   