<div id="loginbox">            

        <?php echo $this->message($this->message); ?>
    
                <?php echo $this->form()->openTag($form); ?>
				 <div class="control-group normal_text"> 
                                     <h3>FSi Pedidos</h3></div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on"><i class="icon-user"></i></span>
                            <?php echo $this->formInput($form->get('username')); ?>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on"><i class="icon-lock"></i></span>
                            <?php echo $this->formInput($form->get('password')); ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <span class="pull-left">
                        <a href="#" class="flip-link btn btn-inverse" id="to-recover">Recuperar senha?</a></span>
                    <span class="pull-right">
                        <?php echo $this->formInput($form->get('submit')); ?>
                    </span>
                </div>
            <?php echo $this->form()->closeTag(); ?>
    <form id="recoverform" action="/auth/recover" method="POST" class="form-vertical">
				<p class="normal_text">Entre com seu email para receber as instruções para alterar sua senha.</p>
				
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on"><i class="icon-envelope"></i></span>
                            <input type="text" name="ds_email" placeholder="E-mail" />
                        </div>
                    </div>
               
                <div class="form-actions">
                    <span class="pull-left"><a href="#" class="flip-link btn btn-inverse" id="to-login">&laquo; Voltar para login</a></span>
                    <span class="pull-right"><input type="submit" class="btn btn-info" value="Recuperar" /></span>
                </div>
            </form>
            <div class="row-fluid" style="color:#ffffff;margin-left: 20px">
            <div id="footer" class="span12"> 2013 &copy; FSiPedidos. &nbsp; Copyright: <a href="http://fsitecnologia.com.br">FSiTecnologia</a> Versão: <?php echo VERSAO; ?> </div>
        </div>
        </div>
                

