<script src="/js/lightbox.js" type="text/javascript" charset="utf-8"></script>
<link href="/css/lightbox.css" rel="stylesheet" />

<style>
    textarea {resize: none;height: 150px}
    .control-label{font-weight: bold !important}
</style>

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/representadas/index" title="Lista de Representada" class="tip-bottom">
            <i class="icon-thumbs-up"></i> Representada</a>
        <a href="/representadas/detalhes/<?php echo $this->id; ?>" title="Detalhes Representada (<?php echo $oRepresentada->getNoRepresentada(); ?>)" class="tip-bottom current">Detalhes (<?php echo $oRepresentada->getNoRepresentada(); ?>)</a>
    </div>
  </div>
<div class="widget-content">
<p>
    <a href="<?php echo $this->url('produtos', array('action' => 'novo', 'idrep' => $this->id)); ?>" class="btn btn-primary">Adicionar Produto</a>
    <a href="<?php echo $this->url('representadas', array('action' => 'pedidos', 'id' => $this->id)); ?>" class="btn btn-success">Lista Pedidos</a>
    <!--<a href="<?php echo $this->url('produtos', array('action' => 'novo', 'idrep' => $this->id)); ?>" class="btn btn-info">Importar Produto</a>-->
    <a href="<?php echo $this->url('representadas', array('action' => 'editar', 'id' => $this->id)); ?>" class="btn btn-warning">Editar Representada</a>
    <a href="<?php echo $this->url('representadas'); ?>" class="btn">Voltar</a>
           
</p>
</div>

<div class="container-fluid">    
<div class="row-fluid">       
<div class="span7">
     <?php echo $this->message($this->message); ?>
    <div class="widget-box">
        <div class="widget-title">
                <span class="icon">
                        <i class="icon-arrow-right"></i>
                </span>
                <h5>Produtos</h5>
        </div>        
        <div class="widget-content nopadding">
           
                <table class="table table-bordered">
                        <thead>
                                <tr>
                                        <th>&nbsp;</th>
                                        <th>Nome</th>
                                        <th>Valor</th>
                                        <th>&nbsp;</th>
                                </tr>
                        </thead>
                        <tbody>
                            <?php foreach($produtos as $oProduto){?>
                                <tr>
                                    <td>
                                        <div class="user-thumb">
                                            <a href="/produto/<?php echo $oProduto->getImagem(); ?>" rel="lightbox" > 
                                                <img alt="Imagem Produto" src="/produto/thumb_<?php echo $oProduto->getImagem(); ?>"> 
                                            </a>
                                        </div>
                                    </td>
                                    <td><?php echo $oProduto->getNoProduto(); ?><br></td>
                                    <td><?php echo $oProduto->getNoMoeda(); ?> <?php echo $oProduto->getDsValor(); ?>
                                    
                                    <?php if($oProduto->getTpMoeda() == 2){ ?>
                                        / R$ <?php echo $oProduto->getDsValorRealConvertido();?>
                                    <?php } ?>
                                    </td>
                                    <td>
                                
                                            <a href="<?php echo $this->url('produtos', array('action' => 'editar', 'idrep' => $id,'id'=>$oProduto->getCoProduto())); ?>" class="btn btn-primary btn-mini">Alterar</a> 
                                            <a href="<?php echo $this->url('produtos', array('action' => 'deletar', 'idrep' => $id,'id'=>$oProduto->getCoProduto())); ?>" class="btn btn-danger btn-mini">Excluir</a>
                                    </td>
                                </tr>
                            <?php } ?>
                               
                                
                        </tbody>
                </table>
        </div>
</div>
</div>
     
      <div class="span4">
        <div class="widget-box">
          <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
            <h5>Detalhes da Representada</h5>
          </div>
            <form method="POST" action="<?php echo $this->url('representadas', array('action' => 'adicionar')); ?>" class="form-horizontal">
             <div class="widget-content nopadding">
                <div class="control-group">
                <label class="control-label">Razão Social:</label>
                <div class="controls">
                    <?php echo $this->form->getDsRazaoSocial();?>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label">Nome Fantasia:</label>
                <div class="controls">
                    <?php echo $this->form->getNoRepresentada();?>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label">CNPJ</label>
                <div class="controls">
                    <?php echo $this->form->getNuCnpj();?>
                </div>
              </div>
             </div>
             <div class="widget-content nopadding">
                <div class="control-group">
                <label class="control-label">Comissão:</label>
                <div class="controls">
                    <?php echo $this->form->getNuComissao();?>
                    <span class="add-on">%</span> 
                </div>
              </div>
             </div>
             <div class="widget-content nopadding">
                <div class="control-group">
                <label class="control-label">Informações Adicionais:</label>
                <div class="controls">
                    <?php echo $this->form->getDsInfoAdicionais();?>
                </div>
              </div>
             </div>     
           </form> 

        </div>
      </div>   
       
        
        
        
    </div>
    <hr>     
</div>

