<script src="/js/maruti.form_common.js"></script>
<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script>
    $(document).ready(function(){
      $("#basic_validate_telefone").validate({
               
		rules:{
			nu_telefone:{
				required:true
			}
		},
		errorClass: "help-inline",
		errorElement: "span",
		highlight:function(element, errorClass, validClass) {
			$(element).parents('.control-group').addClass('error');
		},
		unhighlight: function(element, errorClass, validClass) {
			$(element).parents('.control-group').removeClass('error');
			$(element).parents('.control-group').addClass('success');
		}
	});
        
        $(".nu_telefone").mask("(99) 9999-9999"); 
    });
</script>
<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/clientes/index" title="Lista de Clientes" class="tip-bottom">
            <i class="icon-user"></i> Clientes</a>
        <a href="<?php echo $this->url('clientes', array('action' => 'detalhes', 'id' => $idcli)); ?>" title="Detalhes Cliente" class="tip-bottom">
            <i class="icon-user"></i>  <?php echo $cliente->getNoCliente();?></a>
        <a href="<?php echo $this->url('telefones', array('action' => 'novo', 'idcli' => $idcli)); ?>" title="Cadastro de Telefone" class="tip-bottom">Novo Telefone</a>
    </div>
</div>
 <div class="container-fluid">
        <div class="row-fluid">
          <div class="span6">
            <div class="widget-box">
              <div class="widget-title"> <span class="icon"> 
                      <i class="icon-align-justify"></i> </span>
                        <h5>Cadastro de Telefone</h5>
              </div>
              <div class="widget-content nopadding">
                <form method="POST" class="form-horizontal" action="<?php echo $this->url('telefones', array('action' => 'adicionar')); ?>" name="basic_validate_telefone" id="basic_validate_telefone" novalidate="novalidate">
                    <input type="hidden" name="co_pessoa" value="<?php echo $idcli; ?>" />
                    <div class="control-group">
                    <label class="control-label" id="no_telefone">Nome do Contato:</label>
                    <div class="controls">
                      <input type="text" name="no_telefone" class="span7" placeholder="" id="required" />
                    </div>
                  </div>
                    <div class="control-group">
                    <label class="control-label" id="nu_telefone">Telefone:</label>
                    <div class="controls">
                      <input type="text" name="nu_telefone" class="span7 nu_telefone" placeholder="" id="required" />
                    </div>
                  </div>                   
                  <div class="form-actions">
                     <button type="submit" class="btn btn-success">Salvar</button>
                    <a href="<?php echo $this->url('clientes', array('action' => 'detalhes', 'id' => $idcli)); ?>" class="btn">Voltar</a>
                  </div>
               </form> 
              </div>
            </div>
          </div>        
        </div>
        <hr>     
</div>   