<!DOCTYPE html>
<html lang="en">
    
<head>
        <?php echo $this->headTitle(TITULO_SISTEMA); ?>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/css/bootstrap-responsive.min.css" />
        <link rel="stylesheet" href="/css/maruti-login.css" />
        
    </head>
    <body> 
        
          <?php echo $content; ?>     
        <script src="/js/jquery.min.js"></script>  
        <script src="/js/maruti.login.js"></script> 
    </body>

</html>
