<!DOCTYPE html>
<html lang="en">
<head>
<?php echo $this->headTitle(TITULO_SISTEMA); ?>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="/css/bootstrap.min.css" />
<link rel="stylesheet" href="/css/bootstrap-responsive.min.css" />
<link rel="stylesheet" href="/css/fullcalendar.css" />
<link rel="stylesheet" href="/css/maruti-style.css" />
<link rel="stylesheet" href="/css/maruti-media.css" class="skin-color" />


<script src="/js/jquery-1.9.1.min.js"></script> 
<script src="/js/bootstrap.min.js"></script> 

</head>
<body>

<!--Header-part-->
<div id="header">
  <h1><a href="dashboard.html">Maruti Admin</a></h1>
</div>
<!--close-Header-part--> 

<!--top-Header-messaages-->
<div class="btn-group rightzero"> <a class="top_message tip-left" title="Manage Files"><i class="icon-file"></i></a> <a class="top_message tip-bottom" title="Manage Users"><i class="icon-user"></i></a> <a class="top_message tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a> <a class="top_message tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a> </div>
<!--close-top-Header-messaages--> 

<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <!-- <li class="" >
        <a title="" href="#">
            <i class="icon icon-user"></i> 
            <span class="text">Profile</span>
        </a>
    </li>
    <li class=" dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a class="sAdd" title="" href="#">new message</a></li>
        <li><a class="sInbox" title="" href="#">inbox</a></li>
        <li><a class="sOutbox" title="" href="#">outbox</a></li>
        <li><a class="sTrash" title="" href="#">trash</a></li>
      </ul>
    </li>
    <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
    -->
    <li class=""><a title="" href="/user/logout"><i class="icon icon-share-alt"></i> <span class="text">Sair</span></a></li>
  </ul>
</div>
<!--close-top-Header-menu-->

<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a><ul>
    <li class="active"><a href="/"><i class="icon icon-home"></i> <span>Dashboard</span></a> </li>
    <li> <a href="/pedidos"><i class="icon icon-inbox"></i> <span>Pedidos</span></a> </li>
    <li> <a href="/clientes"><i class="icon icon-user"></i> <span>Clientes</span></a> </li>
    <li><a href="/representadas"><i class="icon icon-thumbs-up"></i> <span>Representadas</span></a></li>
    <li><a href="/colaboradores"><i class="icon icon-fullscreen"></i> <span>Colaboradores</span></a></li>
    <li> <a href="/comissoes"><i class="icon icon-briefcase"></i> <span>Comissões</span> 
            </a>
     
    </li>
    <li  class="submenu"><a href="/relatorios"><i class="icon icon-signal"></i> <span>Relatórios</span></a>
        <ul>
        <li><a href="form-common.html">Pedido Faturado</a></li>
        <li><a href="form-validation.html">Faturamento <span class="label label-important">3</span></a></li>
      </ul>
    </li>
    
  </ul>
</div>
<div id="content">
  <?php echo $this->content; ?>
</div>
</div>
</div>
<div class="row-fluid">
  <div id="footer" class="span12"> 2013 &copy; FSiPedidos. Todos Direitos reservados <a href="http://fsitecnologia.com.br">FSiTecnologia</a> </div>
</div>

</body>
</html>
