<script src="/js/bootstrap-datepicker.js"></script> 
<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script>
    $(document).ready(function(){
        $('.datepicker').datepicker();
        $("#cnpj").mask("99.999.999/9999-99"); 
        $("#cpf").mask("999.999.999-99"); 
    });

</script>
    

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Home" class="tip-bottom"><i class="icon-home"></i> Home</a>
        <a href="/clientes/index" title="Lista de Clientes" class="tip-bottom">
            <i class="icon-user"></i> Clientes</a>
        <a href="/clientes/detalhes/<?php echo $this->id; ?>" title="Detalhes Cliente" class="tip-bottom">Detalhes</a>
    </div>
  </div>
 <div class="container-fluid">
        <div class="row-fluid">
          <div class="span6">
            <div class="widget-box">
              <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Cadastro de Cliente</h5>
              </div>
              <div class="widget-content nopadding">
                <form method="POST" action="<?php echo $this->url('clientes', array('action' => 'atualizar')); ?>" class="form-horizontal">
                    <input type="hidden" name="co_cliente" value="<?php echo $this->id; ?>">
                   <div class="control-group">
                <label class="control-label">Tipo de Pessoa</label>
                <div class="controls">
                  <label>
                      <?php if($this->oCliente->getTipoCliente() == "J"){ ?>Pessoa Jurídica<?php } ?> 
                      <?php if($this->oCliente->getTipoCliente() == "F"){ ?>Pessoa Física<?php } ?> 
                  </label>
                </div>
              </div>
                    <div class="control-group" id="r_social"> 
                    <label class="control-label">Razão Social:</label>
                    <div class="controls">
                      <?php echo $this->oCliente->getDsRazaoSocial(); ?>
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label" id="no_cliente_label">Nome Fantasia:</label>
                    <div class="controls">
                     <?php echo $this->oCliente->getNoCliente(); ?>
                    </div>
                  </div>
                  <div class="control-group" id="cnpj_line">
                    <label class="control-label">CNPJ</label>
                    <div class="controls">
                      <?php echo $this->oCliente->getNuCnpj(); ?>
                    </div>
                  </div>
                    <div class="control-group"  id="cpf_line" style="display:none">
                    <label class="control-label">CPF</label>
                    <div class="controls">
                      <?php echo $this->oCliente->getNuCpf(); ?>
                    </div>
                  </div>
                  <div class="control-group" id="i_estadual">
                    <label class="control-label">Inscrição Estadual:</label>
                    <div class="controls">
                      <?php echo $this->oCliente->getDsInscricaoEstadual(); ?>
                    </div>
                  </div>
                  <div class="control-group" id="ramo_atividade">
                    <label class="control-label">Ramo de atividade:</label>
                    <div class="controls">
                      <?php echo $this->oCliente->getDsRamoAtividade(); ?>
                      
                  </div>       
                  <div class="control-group" id="data_fundacao">
                    <label class="control-label">Data de Fundação</label>
                    <div class="controls">
                      
                        <?php echo $this->oCliente->getDtFundacao('d/m/Y'); ?>
                       
                    </div>
                  </div>    
                  <div class="form-actions">
                    <a href="<?php echo $this->url('clientes', array('action' => 'editar', 'id' => $this->id)); ?>" class="btn btn-warning">Editar Contato</a>
                    <a href="<?php echo $this->url('clientes'); ?>" class="btn">Voltar</a>
                  </div>
               </form> 
              </div>
            </div>
          </div>        
        </div>
        <hr>    
     
</div>    

<script src="/js/maruti.form_common.js"></script> 
<script>
    var tipo_pessoa = $("input:radio:checked").val();
       if(tipo_pessoa == "F"){
           $("#no_cliente_label").html("Nome Cliente:");
           $("#r_social").css({'display':'none'});
           $("#i_estadual").css({'display':'none'});
           $("#cnpj_line").css({'display':'none'});
           $("#cpf_line").css({'display':''});
           $("#data_fundacao").css({'display':'none'});
       }
       if(tipo_pessoa == "J"){
           $("#no_cliente_label").html("Nome Fantasia:");
           $("#r_social").css({'display':''});
           $("#i_estadual").css({'display':''});
           $("#cnpj_line").css({'display':''});
           $("#cpf_line").css({'display':'none'});
           $("#data_fundacao").css({'display':''});
       }   
</script>
