<script src="/js/bootstrap-datepicker.js"></script> 
<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script>
    $(document).ready(function(){
        $('.datepicker').datepicker();
        $("#cnpj").mask("99.999.999/9999-99"); 
        $("#cpf").mask("999.999.999-99"); 
    });
    
 $(document).ready(function() {
    $('input:radio').change(function() {
       if($(this).val() == "F"){
           $("#no_cliente_label").html("Nome Cliente:");
           $("#r_social").css({'display':'none'});
           $("#i_estadual").css({'display':'none'});
           $("#cnpj_line").css({'display':'none'});
           $("#cpf_line").css({'display':''});
           $("#data_fundacao").css({'display':'none'});
       }
       if($(this).val() == "J"){
           $("#no_cliente_label").html("Nome Fantasia:");
           $("#r_social").css({'display':''});
           $("#i_estadual").css({'display':''});
           $("#cnpj_line").css({'display':''});
           $("#cpf_line").css({'display':'none'});
           $("#data_fundacao").css({'display':''});
       }       
    });
});
</script>
    

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Home" class="tip-bottom"><i class="icon-home"></i> Home</a>
        <a href="/clientes/index" title="Lista de Clientes" class="tip-bottom">
            <i class="icon-user"></i> Clientes</a>
        <a href="/clientes/novo" title="Cadastro de Cliente" class="tip-bottom">Novo</a>
    </div>
  </div>
 <div class="container-fluid">
        <div class="row-fluid">
          <div class="span6">
            <div class="widget-box">
              <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Cadastro de Cliente</h5>
              </div>
              <div class="widget-content nopadding">
                <form method="POST" action="<?php echo $this->url('clientes', array('action' => 'adicionar')); ?>" class="form-horizontal">
                   <div class="control-group">
                <label class="control-label">Tipo de Pessoa</label>
                <div class="controls">
                  <label>
                      <input type="radio" name="pessoa_tipo" value="J" checked="true" id="pessoa_tipo" />
                    Pessoa Jurídica</label>
                  <label>
                    <input type="radio" name="pessoa_tipo"  value="F" id="pessoa_tipo" />
                    Pessoa Física</label>
                  
                </div>
              </div>
                    <div class="control-group" id="r_social"> 
                    <label class="control-label">Razão Social:</label>
                    <div class="controls">
                      <input type="text" name="r_social" class="span11" placeholder="Razão Social" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label" id="no_cliente_label">Nome Fantasia:</label>
                    <div class="controls">
                      <input type="text" name="no_cliente" class="span11" placeholder="Nome" />
                    </div>
                  </div>
                  <div class="control-group" id="cnpj_line">
                    <label class="control-label">CNPJ</label>
                    <div class="controls">
                      <input type="text" name="cnpj" id="cnpj"  class="span11" placeholder="CNPJ"  />
                    </div>
                  </div>
                    <div class="control-group"  id="cpf_line" style="display:none">
                    <label class="control-label">CPF</label>
                    <div class="controls">
                      <input type="text" name="cpf" id="cpf"  class="span11" placeholder="CPF"  />
                    </div>
                  </div>
                  <div class="control-group" id="i_estadual">
                    <label class="control-label">Inscrição Estadual:</label>
                    <div class="controls">
                      <input type="text" class="span11" name="i_estadual" placeholder="Inscrição Estadual" />
                    </div>
                  </div>
                  <div class="control-group" id="ramo_atividade">
                    <label class="control-label">Ramo de atividade:</label>
                    <div class="controls">
                      <input type="text" class="span11" name="ramo_atividade"  placeholder="Ramo de atividade" />
                      
                  </div>       
                  <div class="control-group" id="data_fundacao">
                    <label class="control-label">Data de Fundação</label>
                    <div class="controls">
                      <div data-date="01/01/2013" class="input-append date datepicker">
                        <input type="text" value="01/01/2013" name="dt_criacao"   data-date-format="mm-dd-yyyy" class="span11" >
                        <span class="add-on"><i class="icon-th"></i></span> </div>
                    </div>
                  </div>    
                  <div class="form-actions">
                    <button type="submit" class="btn btn-success">Salvar</button>
                    <a href="<?php echo $this->url('clientes'); ?>" class="btn">Voltar</a>
                  </div>
               </form> 
              </div>
            </div>
          </div>        
        </div>
        <hr>    
     
</div>    

<script src="/js/maruti.form_common.js"></script> 