 <div id="content-header">
    <div id="breadcrumb"> <a href="/" title="Principal" class="tip-bottom current">
            <i class="icon-home"></i> Principal </a></div>
  </div>
  <div class="container-fluid">
   	<div class="quick-actions_homepage">
    <ul class="quick-actions">
          <li> <a href="/pedidos"> <i class="icon-shopping-bag"></i> Pedidos </a> </li>
          <li> <a href="/representadas"> <i class="icon-survey"></i> Representadas </a> </li>
          <li> <a href="/clientes"> <i class="icon-people"></i> Clientes </a> </li>
          <li> <a href="/relatorios"> <i class="icon-graph"></i>Relatórios</a> </li>
        </ul>
   </div>
   
    <hr>
  
    
  </div>