<script src="/js/lightbox.js" type="text/javascript" charset="utf-8"></script>
<link href="/css/lightbox.css" rel="stylesheet" />
<script>
    function saveStatus(){
        $('#target').submit();
    }
</script>
<style>
    textarea {resize: none;height: 150px}
    .control-label{font-weight: bold !important}
    .alert { margin-top: 20px !important }
    select {border:0px !important;}
    
</style>

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/pedidos/index" title="Pedido    " class="tip-bottom">
            <i class="icon-thumbs-up"></i> Pedido</a>
        <a href="/pedidos/detalhes/<?php echo $this->id; ?>" title="Detalhes do Pedido" class="tip-bottom current">Detalhes</a>
    </div>
  </div>
<div class="widget-content">
    <form id="target" method="POST" action="<?php echo $this->url('pedidos', array('action' => 'detalhes','id'=>$id)); ?>" class="form-horizontal">
        <input type="hidden" value="<?php echo $id;?>" name="id">
        <div class="btn-group">
            <a href="<?php echo $this->url('pedidos', array('action' => 'novo-produto', 'id' => $this->id)); ?>" class="btn btn-primary">Produto</a>
        </div>
        <div class="btn-group">
            <a href="<?php echo $this->url('pedidos', array('action' => 'nova-nota-fiscal', 'id' => $this->id)); ?>" class="btn btn-primary">Nota Fiscal</a>
        </div>
        <div class="btn-group">
            <a href="<?php echo $this->url('pedidos', array('action' => 'novo-boleto', 'id' => $this->id)); ?>" class="btn btn-primary">Boleto</a>
        </div>
        <!--<a href="<?php echo $this->url('produtos', array('action' => 'novo', 'idrep' => $this->id)); ?>" class="btn btn-info">Importar Produto</a>-->
        <div class="btn-group">
            <a target="_Blank" href="<?php echo $this->url('report', array('action' => 'pedido-pdf', 'id' => $this->id,'nome'=>$nomePedido)); ?>" class="btn btn-success">Imprimir Pedido</a>
        </div>
        <div class="btn-group">
            <select class="btn btn-warning" name="co_status" onchange="saveStatus()" style="text-align: left">
            <?php 
                 if($oStatus){ 
                     foreach($oStatus as $Status){ ?>
                <option <?php if($Status->getCoStatus() == $CoStatus){ ?> selected="selected" <?php } ?> value="<?php echo $Status->getCoStatus(); ?>"><?php echo $Status->getNoStatus(); ?></option>   
                 <?php }} ?>
            </select>
        </div>
        <div class="btn-group">
            <a href="<?php echo $this->url('pedidos'); ?>" class="btn">Voltar</a>>
        </div>
    </form>

<div class="container-fluid">    
<div class="row-fluid">       
<div class="span7">
    <form method="POST" action="<?php echo $this->url('pedidos', array('action' => 'detalhes','id'=>$id)); ?>" class="form-horizontal">
        <input type="hidden" value="<?php echo $id;?>" name="id">
     <?php echo $this->message($this->message); ?>
     <div class="widget-box ">
        <div class="widget-title">
                <span class="icon">
                        <i class="icon-arrow-right"></i>
                </span>
                <h5>Produtos</h5> 
                <button type="submit" class="btn-mini btn-success" style="top: 6px;position: absolute;">Atualizar</button>
        </div>        
        
        <div class="widget-content nopadding">
           
           <table class="table table-bordered table-striped">
                      <thead>
                        <tr>
                          <th>Qnt.</th>
                          <th>Qnt. Entregue</th>
                          <th>V. Original</th>
                          <th>Desc</th>
                          <th>Comissão</th>
                          <th>Total Orig.</th>
                          <th>Total Entreg.</th>
                          <!--<th>Ação</th>-->
                        </tr>
                      </thead>
                      <tbody>
                           <?php 
                        if($oProdutoPedido){ 
                            foreach($oProdutoPedido as $oProdutoP){ ?>
                          <tr class="odd gradeX">
                              <td colspan="7"><b>Produto:</b> <?php echo $oProdutoP->getNoProduto(); ?> </td>
                          </tr>
                        <tr class="odd gradeX">
                          <td><?php echo $oProdutoP->getQntOriginal(); ?></td>
                          <td>
                              <input class="input-mini" type="text" value="<?php echo $oProdutoP->getQntEntregue(); ?>" name="qnt_entregue[<?php echo $oProdutoP->getCoProduto();?>]">                              
                          </td>
                          <td><?php echo $oProdutoP->getNoMoeda() . " " . PedidoPeer::convertMoedaCasaDecimal($oProdutoP->getVlOriginal()); ?></td>
                          <td><?php echo $oProdutoP->getVlDesconto(); ?>%</td>
                          <td><?php echo $oProdutoP->getVlComissao(); ?>%</td>
                          <td><?php echo $oProdutoP->getNoMoeda() . " " .PedidoPeer::convertMoedaCasaDecimal($oProdutoP->getTotal()); ?></td>
                          <td><?php echo $oProdutoP->getNoMoeda() . " " .PedidoPeer::convertMoedaCasaDecimal($oProdutoP->getTotalEntregue()); ?></td>
                          
                          <!--<td><a href="<?php echo $this->url('pedidos',array('action'=>'apagar-produto-pedido','id'=>$id,'produto'=>$oProdutoP->getCoProduto())); ?>" class="btn btn-mini">Apagar</a></td>-->
                        </tr>
                        <?php } } ?>
                      </tbody>
                    </table>
        </div>
</div>
    </form>
</div>
     
      <div class="span4">
          <div class="widget-box form-horizontal">
          <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
            <h5>Detalhes do Cliente</h5>
          </div>
             <div class="widget-content nopadding">
                <div class="control-group">
                <label class="control-label">Razão Social:</label>
                <div class="controls">
                    <?php echo $oCliente->getDsRazaoSocial();?>
                </div>
              </div>
                <div class="control-group">
                <label class="control-label">CNPJ:</label>
                <div class="controls">
                    <?php echo $oCliente->getNuCnpj();?>
                </div>
              </div>
        </div>
      </div>   
        
        <div class="widget-box form-horizontal" >
          <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
            <h5>Detalhes da Representada</h5>
          </div>
             <div class="widget-content nopadding">
                <div class="control-group">
                <label class="control-label">Razão Social:</label>
                <div class="controls">
                    <?php echo $oRepresentada->getDsRazaoSocial();?>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label">CNPJ</label>
                <div class="controls">
                    <?php echo $oRepresentada->getNuCnpj();?>
                </div>
              </div>
             </div>
       
        </div>
          <?php if($oTransportadora){ ?>
        <div class="widget-box form-horizontal" >
          <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
            <h5>Detalhes da Transportadora</h5>
          </div>
             <div class="widget-content nopadding">
                <div class="control-group">
                <label class="control-label">Nome:</label>
                <div class="controls">
                    <?php echo $oTransportadora->getNoTransportadora();?>
                </div>
              </div>
              <div class="control-group">
                <label class="control-label">Site</label>
                <div class="controls">
                    <a href="<?php echo $oTransportadora->getNoSite();?>" target="_Blank"><?php echo $oTransportadora->getNoSite();?></a>
                </div>
              </div>
             </div>
       
        </div>
          <?php } ?>
    </div>
    <hr>     
</div>

</div>
