<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script src="/js/jquery.maskMoney.js" type="text/javascript"></script>

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/pedidos/index" title="Lista de Pedidos" class="tip-bottom">
            <i class="icon-inbox"></i> Pedidos</a>
        <a href="/pedidos/informacoes-adicionais/<?php echo $id;?>" title="Informações Adicionais" class="tip-bottom current">Pedido (<?php echo $id; ?>) - Cadastro de Produto</a>
    </div>
  </div>
<br>
     
 <div class="container-fluid">
   
        <div class="row-fluid">
          <div class="span6">                 
            <div class="progress progress-info">
                    <div class="bar" style="width: 100%;">
                                <b style="float: left; margin-left: 30px;">1 - Representada e Cliente </b>
                                <b style="float: left; margin-left: 40px;">2 - Cadastro Produto</b>
                                <b style="float: left; margin-left: 40px;">3 - Informações Adicionais</b>
                    </div>
            </div>             
            <div class="widget-box">
              <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Informações Adicionais - Representada: <?php echo $oRepresentada->getNoRepresentada(); ?></h5>
              </div>
            
              <div class="widget-content nopadding">
                  
               
                 <form method="POST" action="<?php echo $this->url('pedidos', array('action' => 'adicionar-informacoes')); ?>" class="form-horizontal"  name="basic_validate_pedido" id="basic_validate_pedido" novalidate="novalidate">
                     <input type="hidden"  class="span4"  name="co_pedido" id="co_pedido" value="<?php echo $id; ?>">
                 
                  <div class="control-group">
                    <label class="control-label">Informações:</label>
                    <div class="controls" id="addQuantidade">                        
                            <textarea  class="span11"  name="ds_informacao" id="ds_informacao"></textarea>
                    </div>
                  </div>
                    <div class="control-group">
                    <label class="control-label">Transportadora:</label>
                    <div class="controls">       
                        <select name="co_transportadora" id="co_transportadora">
                            <option value=""></option>
                          <?php 
                         if($transportadora){ 
                             foreach($transportadora as $oTransportadora){ ?>
                            <option value="<?php echo $oTransportadora->getCoTransportadora(); ?>"><?php echo $oTransportadora->getNoTransportadora(); ?></option>
                        <?php } } ?>
                        </select>
                    </div>
                  </div>
                  <div class="form-actions">
                    <button type="submit" class="btn btn-success">Gerar Pedido  </button>
                    <a href="<?php echo $this->url('pedidos'); ?>" class="btn">Cancelar</a>
                  </div>
                </div>
                 </form>
              </div>
            </div>
            
           
          </div>
            
        </div>
        
</div>    

<script src="/js/maruti.form_common.js"></script>  
