<script src="/js/maruti.form_common.js"></script>
<script src="/js/jquery.maskedinput.js" type="text/javascript"></script>
<script>
$(document).ready(function(){

      $("#basic_validate_pedido").validate({
               
		rules:{
			co_representada:{
				required:true
			},
			co_cliente:{
				required:true
			}
		},
		errorClass: "help-inline",
		errorElement: "span",
		highlight:function(element, errorClass, validClass) {
			$(element).parents('.control-group').addClass('error');
		},
		unhighlight: function(element, errorClass, validClass) {
			$(element).parents('.control-group').removeClass('error');
			$(element).parents('.control-group').addClass('success');
		}
	});

    });

</script>
<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Principal" class="tip-bottom"><i class="icon-home"></i> Principal</a>
        <a href="/pedidos/index" title="Lista de Pedidos" class="tip-bottom">
            <i class="icon-inbox"></i> Pedidos</a>
        <a href="/pedidos/novo" title="Novo Pedido" class="tip-bottom current">Novo</a>
    </div>
  </div>
<br>
     
 <div class="container-fluid">
   
        <div class="row-fluid">
          <div class="span6">
                 
<div class="progress progress-info">
        <div class="bar" style="width: 30%;">
                    <b style="float: left; margin-left: 30px;">1 - Representada e Cliente </b>
        </div>
    </div>
             
            <div class="widget-box">
              <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Cadastro de Pedido</h5>
              </div>
            
              <div class="widget-content nopadding">
                  
               
                 <form method="POST" action="<?php echo $this->url('pedidos', array('action' => 'adicionar')); ?>" class="form-horizontal"  name="basic_validate_pedido" id="basic_validate_pedido" novalidate="novalidate">
                  <div class="control-group">
                    <label class="control-label">Representada:</label>
                    <div class="controls">       
                        <select name="co_representada" id="required">
                         <?php if($representada){ foreach($representada as $oRepresentada){ ?>
                            <option value="<?php echo $oRepresentada->getCoRepresentada(); ?>"><?php echo $oRepresentada->getNoRepresentada(); ?></option>
                        <?php } } ?>
                        </select>
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Cliente:</label>
                    <div class="controls" id="addEmail">
                        <select name="co_cliente" id="required">
                         <?php if($cliente){ foreach($cliente as $oCliente){ ?>
                            <option value="<?php echo $oCliente->getCoCliente(); ?>"><?php echo $oCliente->getNoCliente(); ?></option>
                        <?php } } ?>
                        </select>
                    </div>
                  </div>
                  <div class="form-actions">
                    <button type="submit" class="btn btn-success">Criar</button>
                    <a href="<?php echo $this->url('pedidos'); ?>" class="btn">Cancelar</a>
                  </div>
                </div>
                 </form>
              </div>
            </div>
          </div>        
        </div>
        <hr>    
     
</div>    

<script src="/js/maruti.form_common.js"></script> 