<script src="/js/bootstrap-datepicker.js"></script> 
<script>
    $(document).ready(function(){
        $('.datepicker').datepicker();
    });
</script>
    

<div id="content-header">
    <div id="breadcrumb"> 
        <a href="/" title="Home" class="tip-bottom"><i class="icon-home"></i> Home</a>
        <a href="/pedidos/index" title="Lista de Pedidos" class="tip-bottom">
            <i class="icon-user"></i> Pedidos</a>
        <a href="/pedidos/novo" title="Cadastro de Pedido" class="tip-bottom">Novo</a>
    </div>
  </div>
 <div class="container-fluid">
        <div class="row-fluid">
          <div class="span6">
            <div class="widget-box">
              <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Cadastro de Cliente</h5>
              </div>
              <div class="widget-content nopadding">
                <form method="POST" action="<?php echo $this->url('pedidos', array('action' => 'adicionar')); ?>" class="form-horizontal">
                   <div class="control-group">
                <label class="control-label">Radio inputs</label>
                <div class="controls">
                  <label>
                    <input type="radio" name="radios" />
                    Pessoa Jurídica</label>
                  <label>
                    <input type="radio" name="radios" />
                    Pessoa Física</label>
                  
                </div>
              </div>
                    <div class="control-group">
                    <label class="control-label">Razão Social:</label>
                    <div class="controls">
                      <input type="text" class="span11" placeholder="Razão Social" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Nome Fantasia:</label>
                    <div class="controls">
                      <input type="text" class="span11" placeholder="Nome Fantasia" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">CNPJ</label>
                    <div class="controls">
                      <input type="text"  class="span11" placeholder="CNPJ"  />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Inscrição Estadual:</label>
                    <div class="controls">
                      <input type="text" class="span11" placeholder="Inscrição Estadual" />
                    </div>
                  </div>
                  <div class="control-group">
                    <label class="control-label">Ramo de atividade:</label>
                    <div class="controls">
                      <input type="text" class="span11" />
                      <span class="help-block">Ramo de atividade</span> </div>
                  </div>       
                  <div class="control-group">
                    <label class="control-label">Data de Fundação</label>
                    <div class="controls">
                      <div data-date="01/01/2013" class="input-append date datepicker">
                        <input type="text" value="01/01/2013"  data-date-format="mm-dd-yyyy" class="span11" >
                        <span class="add-on"><i class="icon-th"></i></span> </div>
                    </div>
                  </div>    
                  <div class="form-actions">
                    <button type="submit" class="btn btn-success">Save</button>
                    <a href="<?php echo $this->url('pedidos'); ?>" class="btn">Voltar</a>
                  </div>
               </form> 
              </div>
            </div>
          </div>        
        </div>
        <hr>    
     
</div>    

<script src="/js/maruti.form_common.js"></script> 